import type { AuditRecord, DocumentRecord, SignatureRecord, SignatureType } from "./dms-types";

export const lifecycle = [
  "Draft",
  "In Review",
  "Approved",
  "Effective",
  "Under Revision",
  "Retired",
] as const;

export const documentTypes = [
  "SOP",
  "STP",
  "BMR",
  "Protocol",
  "Policy",
  "Work Instruction",
  "Specification",
  "Template",
  "Validation Report",
  "Quality Manual",
];

export const departments = [
  "Quality Assurance",
  "Quality Control",
  "Manufacturing",
  "Validation",
  "Regulatory Affairs",
  "Warehouse",
  "Engineering",
  "IT Quality",
];

export const defaultSignatures: SignatureType[] = [
  "Review",
  "Approval",
  "Effective Release",
];

const signatureSeed: SignatureRecord = {
  id: "SIG-2301",
  documentId: "QA-SOP-0142",
  signer: "Priya Nair",
  role: "QA Approver",
  meaning: "Effective Release",
  reason: "Approved controlled copy for effective use",
  timestamp: "2026-02-17 17:42 IST",
  hash: "b6a9-42f1-89ec",
};

export const documentsSeed: DocumentRecord[] = [
  {
    id: "QA-SOP-0142",
    title: "Deviation Handling and CAPA Escalation",
    type: "SOP",
    department: "Quality Assurance",
    owner: "Aarav Mehta",
    status: "Effective",
    revision: "04",
    effectiveDate: "2026-02-18",
    nextReview: "2026-08-18",
    retention: "8 years after retirement",
    risk: "High",
    training: "Complete",
    tags: ["GMP", "CAPA", "Deviation"],
    reviewers: ["QA Head", "Manufacturing", "Regulatory"],
    requiredSignatures: defaultSignatures,
    signatures: [signatureSeed],
    trainingRecords: [
      { group: "QA Investigators", assigned: 18, complete: 18, dueDate: "2026-02-25" },
      { group: "Production Supervisors", assigned: 31, complete: 31, dueDate: "2026-02-25" },
    ],
    changeControl: "CC-2026-0041",
    storage: "Controlled copy",
    lastAction: "Training impact closed",
  },
  {
    id: "QC-STP-0087",
    title: "Assay Method for Finished Product Release",
    type: "STP",
    department: "Quality Control",
    owner: "Neha Iyer",
    status: "In Review",
    revision: "02",
    effectiveDate: "2026-05-30",
    nextReview: "2027-05-30",
    retention: "Product lifecycle + 1 year",
    risk: "Medium",
    training: "Pending",
    tags: ["QC", "Assay", "Release"],
    reviewers: ["QC Manager", "QA Reviewer"],
    requiredSignatures: ["Review", "Approval"],
    signatures: [],
    trainingRecords: [
      { group: "QC Analysts", assigned: 12, complete: 4, dueDate: "2026-06-03" },
    ],
    changeControl: "CC-2026-0092",
    storage: "Working draft",
    lastAction: "Second reviewer assigned",
  },
  {
    id: "MFG-BMR-0211",
    title: "Batch Manufacturing Record - Tablet Line 2",
    type: "BMR",
    department: "Manufacturing",
    owner: "Rohan Shah",
    status: "Approved",
    revision: "01",
    effectiveDate: "2026-06-01",
    nextReview: "2026-12-01",
    retention: "Batch expiry + 1 year",
    risk: "High",
    training: "Pending",
    tags: ["Batch", "Compression", "Packaging"],
    reviewers: ["Production Head", "QA Approver"],
    requiredSignatures: defaultSignatures,
    signatures: [
      {
        id: "SIG-2304",
        documentId: "MFG-BMR-0211",
        signer: "Rohan Shah",
        role: "Document Owner",
        meaning: "Review",
        reason: "Manufacturing content verified",
        timestamp: "2026-05-14 09:30 IST",
        hash: "d938-6ac4-230b",
      },
      {
        id: "SIG-2305",
        documentId: "MFG-BMR-0211",
        signer: "Priya Nair",
        role: "QA Approver",
        meaning: "Approval",
        reason: "Approved for release planning",
        timestamp: "2026-05-14 10:24 IST",
        hash: "fa30-192d-aa75",
      },
    ],
    trainingRecords: [
      { group: "Line 2 Operators", assigned: 44, complete: 19, dueDate: "2026-05-31" },
    ],
    changeControl: "CC-2026-0107",
    storage: "Controlled copy",
    lastAction: "QA approval completed",
  },
  {
    id: "VAL-PROT-0056",
    title: "Cleaning Validation Protocol - Granulation Suite",
    type: "Protocol",
    department: "Validation",
    owner: "Mira Kapoor",
    status: "Under Revision",
    revision: "03",
    effectiveDate: "2025-11-10",
    nextReview: "2026-05-20",
    retention: "Validation lifecycle",
    risk: "Medium",
    training: "Not required",
    tags: ["Validation", "Cleaning", "Protocol"],
    reviewers: ["Validation Lead", "QA Reviewer"],
    requiredSignatures: ["Review", "Approval"],
    signatures: [],
    trainingRecords: [],
    changeControl: "CC-2026-0088",
    storage: "Working draft",
    lastAction: "Revision opened from periodic review",
  },
  {
    id: "REG-POL-0009",
    title: "Regulatory Dossier Document Control Policy",
    type: "Policy",
    department: "Regulatory Affairs",
    owner: "Sara Khan",
    status: "Draft",
    revision: "01",
    effectiveDate: "2026-07-01",
    nextReview: "2027-07-01",
    retention: "Permanent",
    risk: "Low",
    training: "Not required",
    tags: ["Regulatory", "Dossier"],
    reviewers: ["Regulatory Head"],
    requiredSignatures: ["Review", "Approval"],
    signatures: [],
    trainingRecords: [],
    changeControl: "CC-2026-0116",
    storage: "Working draft",
    lastAction: "Draft created",
  },
  {
    id: "WH-WI-0033",
    title: "Warehouse Temperature Excursion Work Instruction",
    type: "Work Instruction",
    department: "Warehouse",
    owner: "Kabir Jain",
    status: "Retired",
    revision: "05",
    effectiveDate: "2024-04-06",
    nextReview: "2026-04-06",
    retention: "6 years after retirement",
    risk: "Medium",
    training: "Complete",
    tags: ["Warehouse", "Temperature"],
    reviewers: ["Warehouse Lead", "QA Approver"],
    requiredSignatures: ["Retirement"],
    signatures: [
      {
        id: "SIG-2240",
        documentId: "WH-WI-0033",
        signer: "Priya Nair",
        role: "QA Approver",
        meaning: "Retirement",
        reason: "Procedure merged into WH-SOP-0048",
        timestamp: "2026-04-06 11:15 IST",
        hash: "41bf-7c93-20de",
      },
    ],
    trainingRecords: [
      { group: "Warehouse Users", assigned: 21, complete: 21, dueDate: "2024-04-15" },
    ],
    changeControl: "CC-2026-0053",
    storage: "Archive",
    lastAction: "Retired after procedure merge",
  },
];

export const auditSeed: AuditRecord[] = [
  {
    id: "AUD-1098",
    action: "E-signature captured",
    actor: "Priya Nair",
    time: "Today, 10:24",
    documentId: "MFG-BMR-0211",
    note: "QA Approval completed with hash fa30-192d-aa75.",
  },
  {
    id: "AUD-1097",
    action: "Reviewer assigned",
    actor: "Neha Iyer",
    time: "Today, 09:50",
    documentId: "QC-STP-0087",
    note: "QC Manager added as primary technical reviewer.",
  },
  {
    id: "AUD-1096",
    action: "Revision opened",
    actor: "Mira Kapoor",
    time: "Yesterday, 16:35",
    documentId: "VAL-PROT-0056",
    note: "Revision opened from periodic review finding.",
  },
  {
    id: "AUD-1095",
    action: "Training closed",
    actor: "Aarav Mehta",
    time: "Yesterday, 12:10",
    documentId: "QA-SOP-0142",
    note: "All impacted users completed read and understand training.",
  },
];
